name: Build
on: [push, pull_request]

jobs:
  build-osx-x64:
    name: Build for osx-x64
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Cache dylibs
      id: cache-osx-x64
      uses: actions/cache@v1
      with:
        path: runtimes
        key: osx-x64-${{ hashFiles('mbedtls/**') }}

    - name: Build libraries (osx-x64)
      if: steps.cache-osx-x64.outputs.cache-hit != 'true'
      env:
        SHARED: 1
      run: |
        make -C mbedtls lib
        mkdir -p runtimes/osx-x64/native
        cp mbedtls/**/*.dylib runtimes/osx-x64/native

    - uses: actions/upload-artifact@v1
      with:
        name: osx-x64-runtimes
        path: runtimes

  pack:
    name: Generate NuGet Package
    needs:
    - build-osx-x64
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/download-artifact@v1
      with:
        name: osx-x64-runtimes
        path: runtimes

    - id: pack
      run: |
        dotnet pack
        echo "::set-output name=file::$(ls *.nupkg)"

    - uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.pack.outputs.file }}
        path: ${{ steps.pack.outputs.file }}
